In [46]:
import regex
import nltk
import numpy

In [2]:
file_name = input("enter file name\n")

enter file name
Brown.txt


In [3]:
file_obj  = open(file_name,'r')

In [4]:
file_data = file_obj.read()

In [15]:
lines = file_data.split('\n')

In [18]:
t_lines = len(lines)

In [67]:
valid_tags = ['N','M','V']
dict_tags = {'N':0 , 'M':1 , 'V':2 }
no_tags = 3

In [117]:
def find_index(vocab_index,token) :
    if len(vocab_index)==0 :
        return [-1,0] 
    else :
        return bst(vocab_index,token,0,len(vocab_index)-1)
    

In [118]:
def bst(vocab_index,token,i,j) :
    
    if(i==j) :
        if vocab_index[i][0]==token :
            return [1,i] 
        elif vocab_index[i][0] < token :
            return [-1,i] 
        else :
            return [-1,i+1]
    else :
        mid = int( (i+j)/2 )
        if vocab_index[mid][0]==token :
            return [1,mid] 
        elif vocab_index[mid][0]<token :
            return bst(vocab_index,token,i,mid-1)
        else :
            return bst(vocab_index,token,mid+1,j)
            

In [120]:
def C_pm(lines) :
    matrix = numpy.empty( (0,no_tags) ,float )
    row_matrix = 0
    vocab_list = []
    for line in lines :
        print(line)
        tokens = line.split(' ')
        for token in tokens :
            parts = token.split('_')
            if len(parts)==2 :
                if parts[1] in valid_tags  :
                    #print(parts[0])
                    index_v = find_index(vocab_list,parts[0]) 
                    #print(index_v)
                    index_c = dict_tags[ parts[1] ]
                    if index_v[0] == 1 :
                        index_r = vocab_list[ index_v[1] ][1] 
                        matrix[ index_r ][index_c] = matrix[ index_r ][index_c] +  1

                    else :
                        detail = [ parts[0] , row_matrix ]
                        vocab_list.insert(index_v[1] , detail )
                        #print(vocab_list)
                        matrix = numpy.append( matrix , numpy.zeros( (1,no_tags) ) , axis=0 )
                        #print(matrix.shape,row_matrix,index_c)
                        matrix[ row_matrix ][index_c] = matrix[ row_matrix ][index_c] +  1
                        row_matrix = row_matrix + 1  

    return [vocab_list,matrix]
C_pm(lines)

mary_N jane_N can_M see_V will_N 
 spot_N will_M see_V mary_N 
will_M jane_N spot_V mary_N 
mary_N will_M pat_V spot_N
[['will', 4], ['spot', 5], ['see', 3], ['pat', 6], ['mary', 0], ['jane', 1], ['can', 2]]
[[4. 0. 0.]
 [2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]
 [1. 3. 0.]
 [2. 0. 1.]
 [0. 0. 1.]]


array([[4., 0., 0.],
       [2., 0., 0.],
       [0., 1., 0.],
       [0., 0., 2.],
       [1., 3., 0.],
       [2., 0., 1.],
       [0., 0., 1.]])

In [ ]:
class stage :
    
    def __init__(self,listt,pr) :
        self.tags = listt 
        self.cur_tag = listt[-1]
        self.prev = pr
        self.numb = 1
        self.index = len(listt) - 1 
        

In [ ]:
def test(em,tm,lines) :
    
    c_m = numpy.zeros( (no_tags,no_tags) , float ) 
    
    for line in lines :
        tokens = line.split(' ')
        words = []
        for token in tokens :
            parts = token.split('_')
            if len(parts)==2 :
                tag = parts[1]
                if tag in valid_tags :
                    words.append(parts)
        
        
        stack = []
        tag_seq = []
        prob = -1 
        index_sen
        tag_list = copy.deepcopy(valid_tags)
        obj = stage(tag_list,'s')
        stack.append(obj)
        while( len(stack) > 0  )
        {
            if( len(stack[-1].tags) > 0 ) :
                if stack[-1].prev == 's' :
                    prob = prob*em[0][ stack[-1].index ]
                else :
                    prob = prob*em[  ]
                prob = prob*find_prob(tm,stack[-1].prev,words[index_sen])
            else :
        }
        
    

In [82]:
def f_e1(lines) :
    matrix = numpy.zeros( (no_tags+1,no_tags+1) , float )
    for line in lines :
        #matrix = numpy.zeros( (no_tags+1,no_tags+1) , float )

        print(line)
        tokens = line.split(' ') 
        print(tokens)
        IsFirst = True
        for index in range(len(tokens)) :
            
            if IsFirst == True :
                parts = tokens[index].split('_')
                if( len(parts)==2 ) :
                    tag = parts[1]
                    if tag in valid_tags :
                        index_c = dict_tags[ tag ]
                        matrix[0][index_c] = matrix[0][index_c] + 1
                        IsFirst = False
            else :
                parts2 = tokens[index].split('_')
                parts1 = tokens[index-1].split('_')
                if len(parts1)==2 and len(parts2)==2 :
                    tag1 = parts1[1]
                    tag2 = parts2[1]
                    if tag1 in valid_tags and tag2 in valid_tags :
                        index_r = dict_tags[ tag1 ]+1
                        index_c = dict_tags[ tag2 ]
                        matrix[index_r][index_c] = matrix[index_r][index_c] + 1
            
        index = len(tokens)-1 
        while(True) :
            parts = tokens[index].split('_')
            if len(parts)==2 :
                tag = parts[1]
                if tag in valid_tags :
                    index_r = dict_tags[ tag ]+1
                    matrix[index_r][no_tags] = matrix[index_r][no_tags] + 1 
                    break 
            index = index-1
    return  matrix
a = f_e1(lines)
print(a)

mary_N jane_N can_M see_V will_N 
['mary_N', 'jane_N', 'can_M', 'see_V', 'will_N', '']
[[1. 0. 0. 0.]
 [1. 1. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
 spot_N will_M see_V mary_N 
['', 'spot_N', 'will_M', 'see_V', 'mary_N', '']
[[2. 0. 0. 0.]
 [1. 2. 0. 2.]
 [0. 0. 2. 0.]
 [2. 0. 0. 0.]]
will_M jane_N spot_V mary_N 
['will_M', 'jane_N', 'spot_V', 'mary_N', '']
[[2. 1. 0. 0.]
 [1. 2. 1. 3.]
 [1. 0. 2. 0.]
 [3. 0. 0. 0.]]
mary_N will_M pat_V spot_N
['mary_N', 'will_M', 'pat_V', 'spot_N']
[[3. 1. 0. 0.]
 [1. 3. 1. 4.]
 [1. 0. 3. 0.]
 [4. 0. 0. 0.]]
[[3. 1. 0. 0.]
 [1. 3. 1. 4.]
 [1. 0. 3. 0.]
 [4. 0. 0. 0.]]


In [57]:
lines = [ "mary_N jane_N can_M see_V will_N " , " spot_N will_M see_V mary_N " , "will_M jane_N spot_V mary_N " ,"mary_N will_M pat_V spot_N"   ]

In [61]:
a = f_e1(lines)

KeyError: ''

In [30]:
data1 = file_data[ 0 : int(t_lines/3) ]
data2 = file_data[ int(t_lines/3) : int((2.0/3)*t_lines)   ]
data3 = file_data[ int( (2.0/3)*t_lines ) ]

In [27]:
C_em(data1)

The_AT Fulton_NP-TL County_NN-TL Grand_JJ-TL Jury_NN-TL said_VBD Friday_NR an_AT investigation_NN of_IN Atlanta's_NP$ recent_JJ primary_NN election_NN produced_VBD ``_`` no_AT evidence_NN ''_'' that_CS any_DTI irregularities_NNS took_VBD place_NN ._.


In [43]:
l=[]

In [44]:
l.insert(0,4)

In [48]:
a = numpy.zeros(4)

In [49]:
a

array([0., 0., 0., 0.])

In [7]:
s=[1,2,3]

In [12]:
s.size()

AttributeError: 'list' object has no attribute 'size'

In [6]:
s

[1]